### ISSUE TITLE
Warning: "certutil" is not available

### ISSUE THREAD

**Issue by gthieleb** [caddy-ansible/caddy-ansible#58]
During caddy install this message pops up:

```
Warning: "certutil" is not available, install "certutil" with "apt install libnss3-tools" or "yum install nss-tools" and try again
```

Proposal: Install libnss3-tools / nss-tools as part of the role.

**Comment by joelnb** [comment]
Hi @gthieleb, thanks for the report. I am open to adding this but if possible can you share any more details about your setup? I have not personally seen this warning ever so I suspect you must be doing something that I am not or it has been added in a recent Caddy version. Is it that you are using self-signed certs & that makes Caddy require this additional tool? I don't think any of the hosts where I use Caddy are set to use self-signed certs in the config.

**Comment by JJJ** [comment]
Caddyfile:

```caddy
localhost
root * ./volumes/site
file_server
```

docker-compose.yml:
```yml
version: "3.9"

services:
  caddy:
    image: caddy:${CADDY_VERSION}
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./volumes/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./volumes/public:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
```

Result:
![jjj-2024-02-14-at-11-36-35-UTC@2x](https://github.com/caddy-ansible/caddy-ansible/assets/88951/f67f97d9-4ebd-4019-bd79-bfac9bd3f793)
