### ISSUE TITLE
Is procps still needed?

### ISSUE THREAD

**Issue by jmbwell** [caddy-ansible/caddy-ansible#60]
According to a comment, `packages-apt.yml` loads `procps` because the `kill` binary is needed in the service file, which I take to mean the `caddy.service` systemd service file. I don't see where in that file the `kill` binary is used, however. IIUC, systemd can send its own SIGTERM etc. and wouldn't necessarily need kill. 

So is procps still needed?

Affected lines:

```
# This is required because it provides the /bin/kill binary used in the service file
- name: Install procps
  ansible.builtin.apt:
    name: procps
    state: present
```

https://github.com/caddy-ansible/caddy-ansible/blob/master/tasks/packages-apt.yml#L8-L14
