### ISSUE TITLE
You need to install "jmespath" prior to running json_query filter

### ISSUE THREAD

**Issue by ciekals11** [caddy-ansible/caddy-ansible#65]
error:
```
TASK [caddy-ansible : Set variable with list of available releases] ************
fatal: [default]: FAILED! => {"msg": "You need to install \"jmespath\" prior to running json_query filter"}
```
Error showed today (18.12.2023r). Previous build was performed 3 days ago (15.12.2023r) without issues

build on image `hashicorp/packer:1.9.1`

packer (`machine.pkr.hcl`):
```
build {
  ......

  provisioner "ansible" {
    user          = "app"
    galaxy_file   = "./ansible/requirements.yml"
    playbook_file = "./ansible/playbook-step-2.yml"
    ansible_env_vars = [
      "ANSIBLE_SSH_ARGS='-oHostKeyAlgorithms=+ssh-rsa -oPubkeyAcceptedKeyTypes=ssh-rsa'",
      "ANSIBLE_HOST_KEY_CHECKING=False"
    ]
    extra_arguments = [
      "--extra-vars",
      "app=${var.app} env=${var.env}"
    ]
  }
```

galaxy file (`requirements.yml`)
```
roles:
- { src: "git+https://github.com/caddy-ansible/caddy-ansible.git" }
```

playbook file (`playbook-step-2.yml`)
```
- name: Provision Image - Step 2
  hosts: all
  become: true
  tasks:
    - name: ensure exists caddy http server
      include_role: role=caddy-ansible
      vars:
        caddy_setcap: true
        caddy_systemd_capabilities_enabled: true
        caddy_systemd_capabilities: "CAP_NET_BIND_SERVICE"
        caddy_config: "{{ lookup('template', 'templates/Caddyfile.j2') }}"

    - name: enabled caddy
      systemd: name=caddy state=started

```
