### ISSUE TITLE
Unable to start service caddy: Job for caddy.service failed because the control process exited with error code.

### ISSUE THREAD

**Issue by Techbrunch** [caddy-ansible/caddy-ansible#68]
Hello,

I ran into the following issue:

```
Unable to start service caddy: Job for caddy.service failed because the control process exited with error code.
```

The problem was that I'm using `caddy_config` to pass a custom config file:

```
---
- ansible.builtin.include_role:
    name: caddy_ansible.caddy_ansible
  vars:
    caddy_config: "{{ lookup('template', 'templates/Caddyfile.j2') }}"
```

When loggin in to the vm I tried to start the service manually and encountered this error:

```
systemctl start caddy
Job for caddy.service failed because the control process exited with error code.
See "systemctl status caddy.service" and "journalctl -xeu caddy.service" for details.
```

The problem is that since the caddyfile was invalid the `StartLimitBurst`(default 5) of the service was reached and the service ended up in failed state.

This can be checked with:

```
systemctl --failed
```

The workaround was to run:

```
systemctl reset-failed caddy.service
```

A nice improvement would be to run `caddy validate` after `Create caddy config`.

What do you think ?
